"""Comprehensive Medical Knowledge Base for RRRIE-CDSS Query Optimization.

Design principles:
  ✦ GENERIC — covers ALL major medical specialties, not specific conditions
  ✦ Organized by specialty for maintainability
  ✦ Includes Turkish medical terms (system handles Turkish patients)
  ✦ Each dictionary serves a specific purpose in the query optimization pipeline

Architecture:
  MEDICAL_SYNONYMS: input term → preferred English search form
  CLINICAL_LINKS: {symptom set} → injected search term
  PUBMED_MESH: input term → official MeSH descriptor name
  BROAD_CATEGORIES: specific diagnosis → broader search category (for retries)
"""

from __future__ import annotations


# ═══════════════════════════════════════════════════════════════════════════
# MEDICAL SYNONYMS — Maps informal/abbreviated/Turkish terms to
# preferred English search forms. Used by _optimize_query_for_tool().
#
# Format: "lowercase_input" → "Preferred English Search Form"
# Longest-match-first search ensures multi-word terms match before singles.
# ═══════════════════════════════════════════════════════════════════════════

MEDICAL_SYNONYMS: dict[str, str] = {

    # ── CARDIOLOGY ──────────────────────────────────────────────
    "myocardial infarction": "myocardial infarction",
    "mi": "myocardial infarction",
    "heart attack": "myocardial infarction",
    "kalp krizi": "myocardial infarction",
    "miyokard enfarktüsü": "myocardial infarction",
    "stemi": "ST elevation myocardial infarction",
    "nstemi": "non-ST elevation myocardial infarction",
    "acute coronary syndrome": "acute coronary syndrome",
    "acs": "acute coronary syndrome",
    "unstable angina": "unstable angina",
    "angina pectoris": "angina pectoris",
    "angina": "angina pectoris",
    "heart failure": "heart failure",
    "chf": "congestive heart failure",
    "congestive heart failure": "congestive heart failure",
    "kalp yetmezliği": "heart failure",
    "cardiac failure": "heart failure",
    "hfref": "heart failure reduced ejection fraction",
    "hfpef": "heart failure preserved ejection fraction",
    "atrial fibrillation": "atrial fibrillation",
    "afib": "atrial fibrillation",
    "af": "atrial fibrillation",
    "aritmi": "arrhythmia",
    "arrhythmia": "arrhythmia",
    "svt": "supraventricular tachycardia",
    "supraventricular tachycardia": "supraventricular tachycardia",
    "ventricular tachycardia": "ventricular tachycardia",
    "vt": "ventricular tachycardia",
    "ventricular fibrillation": "ventricular fibrillation",
    "vf": "ventricular fibrillation",
    "aortic dissection": "aortic dissection",
    "aort diseksiyonu": "aortic dissection",
    "aortic aneurysm": "aortic aneurysm",
    "cardiac tamponade": "cardiac tamponade",
    "pericardial effusion": "pericardial effusion",
    "pericarditis": "pericarditis",
    "perikardit": "pericarditis",
    "myocarditis": "myocarditis",
    "miyokardit": "myocarditis",
    "endocarditis": "infective endocarditis",
    "infective endocarditis": "infective endocarditis",
    "endokardit": "infective endocarditis",
    "bacterial endocarditis": "infective endocarditis",
    "cardiomyopathy": "cardiomyopathy",
    "kardiyomiyopati": "cardiomyopathy",
    "dilated cardiomyopathy": "dilated cardiomyopathy",
    "hypertrophic cardiomyopathy": "hypertrophic cardiomyopathy",
    "deep vein thrombosis": "deep vein thrombosis",
    "dvt": "deep vein thrombosis",
    "derin ven trombozu": "deep vein thrombosis",
    "pulmonary embolism": "pulmonary embolism",
    "pe": "pulmonary embolism",
    "pulmoner emboli": "pulmonary embolism",
    "venous thromboembolism": "venous thromboembolism",
    "vte": "venous thromboembolism",
    "hypertensive crisis": "hypertensive crisis",
    "hypertensive emergency": "hypertensive emergency",
    "hipertansif kriz": "hypertensive crisis",
    "hipertansiyon": "hypertension",
    "hypertension": "hypertension",
    "hypotension": "hypotension",
    "hipotansiyon": "hypotension",
    "bradycardia": "bradycardia",
    "bradikardi": "bradycardia",
    "tachycardia": "tachycardia",
    "taşikardi": "tachycardia",

    # ── PULMONOLOGY ─────────────────────────────────────────────
    "pneumonia": "pneumonia",
    "pnömoni": "pneumonia",
    "community acquired pneumonia": "community-acquired pneumonia",
    "cap": "community-acquired pneumonia",
    "hospital acquired pneumonia": "hospital-acquired pneumonia",
    "hap": "hospital-acquired pneumonia",
    "aspiration pneumonia": "aspiration pneumonia",
    "copd": "chronic obstructive pulmonary disease",
    "koah": "chronic obstructive pulmonary disease",
    "chronic obstructive pulmonary disease": "chronic obstructive pulmonary disease",
    "emphysema": "emphysema",
    "amfizem": "emphysema",
    "chronic bronchitis": "chronic bronchitis",
    "asthma": "asthma",
    "astım": "asthma",
    "status asthmaticus": "status asthmaticus",
    "bronchospasm": "bronchospasm",
    "pneumothorax": "pneumothorax",
    "pnömotoraks": "pneumothorax",
    "tension pneumothorax": "tension pneumothorax",
    "ards": "acute respiratory distress syndrome",
    "acute respiratory distress syndrome": "acute respiratory distress syndrome",
    "pleural effusion": "pleural effusion",
    "plevral efüzyon": "pleural effusion",
    "empyema": "empyema",
    "pulmonary fibrosis": "pulmonary fibrosis",
    "interstitial lung disease": "interstitial lung disease",
    "ild": "interstitial lung disease",
    "lung cancer": "lung neoplasm",
    "akciğer kanseri": "lung neoplasm",
    "bronchogenic carcinoma": "lung neoplasm",
    "hemoptysis": "hemoptysis",
    "hemoptizi": "hemoptysis",
    "dyspnea": "dyspnea",
    "dispne": "dyspnea",
    "nefes darlığı": "dyspnea",
    "respiratory failure": "respiratory failure",
    "solunum yetmezliği": "respiratory failure",

    # ── NEUROLOGY ───────────────────────────────────────────────
    "stroke": "stroke",
    "cva": "stroke",
    "cerebrovascular accident": "stroke",
    "felç": "stroke",
    "inme": "stroke",
    "ischemic stroke": "ischemic stroke",
    "hemorrhagic stroke": "hemorrhagic stroke",
    "tia": "transient ischemic attack",
    "transient ischemic attack": "transient ischemic attack",
    "subarachnoid hemorrhage": "subarachnoid hemorrhage",
    "sah": "subarachnoid hemorrhage",
    "subaraknoid kanama": "subarachnoid hemorrhage",
    "intracerebral hemorrhage": "intracerebral hemorrhage",
    "subdural hematoma": "subdural hematoma",
    "epidural hematoma": "epidural hematoma",
    "meningitis": "meningitis",
    "menenjit": "meningitis",
    "bacterial meningitis": "bacterial meningitis",
    "viral meningitis": "viral meningitis",
    "aseptic meningitis": "aseptic meningitis",
    "meningoencephalitis": "meningoencephalitis",
    "encephalitis": "encephalitis",
    "ensefalit": "encephalitis",
    "viral encephalitis": "viral encephalitis",
    "herpes simplex encephalitis": "herpes simplex encephalitis",
    "hsv encephalitis": "herpes simplex encephalitis",
    "herpes encephalitis": "herpes simplex encephalitis",
    "autoimmune encephalitis": "autoimmune encephalitis",
    "otoimmün ensefalit": "autoimmune encephalitis",
    "anti-nmda receptor encephalitis": "anti-NMDA receptor encephalitis",
    "anti-nmda": "anti-NMDA receptor encephalitis",
    "anti nmda": "anti-NMDA receptor encephalitis",
    "nmda receptor": "anti-NMDA receptor encephalitis",
    "paraneoplastic syndrome": "paraneoplastic syndrome",
    "paraneoplastic encephalitis": "paraneoplastic encephalitis",
    "paraneoplastic": "paraneoplastic syndrome",
    "encephalopathy": "encephalopathy",
    "ensefalopati": "encephalopathy",
    "wernicke encephalopathy": "Wernicke encephalopathy",
    "wernicke-korsakoff": "Wernicke-Korsakoff syndrome",
    "wernicke korsakoff": "Wernicke-Korsakoff syndrome",
    "wernicke": "Wernicke encephalopathy",
    "korsakoff": "Korsakoff syndrome",
    "hepatic encephalopathy": "hepatic encephalopathy",
    "seizure": "seizures",
    "nöbet": "seizures",
    "seizures": "seizures",
    "epilepsy": "epilepsy",
    "sara": "epilepsy",
    "epilepsi": "epilepsy",
    "status epilepticus": "status epilepticus",
    "guillain-barre": "Guillain-Barre syndrome",
    "guillain barre": "Guillain-Barre syndrome",
    "gbs": "Guillain-Barre syndrome",
    "guillain-barre syndrome": "Guillain-Barre syndrome",
    "multiple sclerosis": "multiple sclerosis",
    # "ms" removed — 2-char abbreviation collides with common words via substring match
    "migraine": "migraine",
    "migren": "migraine",
    "cluster headache": "cluster headache",
    "tension headache": "tension-type headache",
    "parkinson": "Parkinson disease",
    "parkinson disease": "Parkinson disease",
    "parkinsonism": "parkinsonism",
    "als": "amyotrophic lateral sclerosis",
    "amyotrophic lateral sclerosis": "amyotrophic lateral sclerosis",
    "motor neuron disease": "motor neuron disease",
    "brain abscess": "brain abscess",
    "beyin apsesi": "brain abscess",
    "cerebral abscess": "brain abscess",
    "normal pressure hydrocephalus": "normal pressure hydrocephalus",
    "nph": "normal pressure hydrocephalus",
    "cerebral venous thrombosis": "cerebral venous thrombosis",
    "cvt": "cerebral venous thrombosis",
    "myasthenia gravis": "myasthenia gravis",
    "nystagmus": "nystagmus",
    "ophthalmoplegia": "ophthalmoplegia",
    "diplopia": "diplopia",
    "ataxia": "ataxia",
    "confusion": "confusion",
    "bilinç bulanıklığı": "altered mental status",
    "altered mental status": "altered mental status",
    "delirium": "delirium",
    "catatonia": "catatonia",
    "psychosis": "psychosis",
    "psikoz": "psychosis",
    "hallucination": "hallucinations",
    "hallucinations": "hallucinations",
    "halüsinasyon": "hallucinations",
    "vertigo": "vertigo",
    "vertij": "vertigo",
    "peripheral neuropathy": "peripheral neuropathy",
    "neuropathy": "peripheral neuropathy",
    "nöropati": "peripheral neuropathy",
    "radiculopathy": "radiculopathy",
    "trigeminal neuralgia": "trigeminal neuralgia",
    "bell palsy": "Bell palsy",
    "facial palsy": "facial paralysis",
    "botulism": "botulism",
    "descending paralysis": "descending paralysis",
    "flaccid paralysis": "flaccid paralysis",
    "autonomic instability": "autonomic dysfunction",
    "autonomic dysfunction": "autonomic dysfunction",
    "autonomic storm": "autonomic dysfunction",
    "orolingual": "orofacial automatisms",
    "automatism": "automatisms",
    "orolingual automatism": "orofacial automatisms",

    # ── GASTROENTEROLOGY ────────────────────────────────────────
    "appendicitis": "appendicitis",
    "apandisit": "appendicitis",
    "acute appendicitis": "acute appendicitis",
    "pancreatitis": "pancreatitis",
    "pankreatit": "pancreatitis",
    "acute pancreatitis": "acute pancreatitis",
    "chronic pancreatitis": "chronic pancreatitis",
    "cholecystitis": "cholecystitis",
    "kolesistit": "cholecystitis",
    "cholelithiasis": "cholelithiasis",
    "safra taşı": "cholelithiasis",
    "choledocholithiasis": "choledocholithiasis",
    "cholangitis": "cholangitis",
    "kolanjit": "cholangitis",
    "gi bleeding": "gastrointestinal hemorrhage",
    "gastrointestinal bleeding": "gastrointestinal hemorrhage",
    "upper gi bleed": "upper gastrointestinal hemorrhage",
    "lower gi bleed": "lower gastrointestinal hemorrhage",
    "melena": "melena",
    "hematochezia": "hematochezia",
    "hematemesis": "hematemesis",
    "bowel obstruction": "intestinal obstruction",
    "ileus": "ileus",
    "barsak tıkanıklığı": "intestinal obstruction",
    "sbo": "small bowel obstruction",
    "small bowel obstruction": "small bowel obstruction",
    "peptic ulcer": "peptic ulcer",
    "gastric ulcer": "gastric ulcer",
    "duodenal ulcer": "duodenal ulcer",
    "ülser": "peptic ulcer",
    "inflammatory bowel disease": "inflammatory bowel disease",
    "ibd": "inflammatory bowel disease",
    "crohn disease": "Crohn disease",
    "crohn": "Crohn disease",
    "ulcerative colitis": "ulcerative colitis",
    "ülseratif kolit": "ulcerative colitis",
    "diverticulitis": "diverticulitis",
    "divertikülit": "diverticulitis",
    "hepatitis": "hepatitis",
    "hepatit": "hepatitis",
    "viral hepatitis": "viral hepatitis",
    "hepatitis a": "hepatitis A",
    "hepatitis b": "hepatitis B",
    "hepatitis c": "hepatitis C",
    "alcoholic hepatitis": "alcoholic hepatitis",
    "cirrhosis": "liver cirrhosis",
    "siroz": "liver cirrhosis",
    "liver cirrhosis": "liver cirrhosis",
    "liver failure": "liver failure",
    "karaciğer yetmezliği": "liver failure",
    "celiac disease": "celiac disease",
    "celiac": "celiac disease",
    "çölyak": "celiac disease",
    "esophageal varices": "esophageal varices",
    "variceal bleeding": "esophageal variceal hemorrhage",
    "ascites": "ascites",
    "asit": "ascites",
    "jaundice": "jaundice",
    "sarılık": "jaundice",
    "diarrhea": "diarrhea",
    "ishal": "diarrhea",
    "constipation": "constipation",
    "kabızlık": "constipation",
    "vomiting": "vomiting",
    "kusma": "vomiting",
    "nausea": "nausea",
    "bulantı": "nausea",
    "abdominal pain": "abdominal pain",
    "karın ağrısı": "abdominal pain",

    # ── ENDOCRINOLOGY ───────────────────────────────────────────
    "diabetes mellitus": "diabetes mellitus",
    "diabetes": "diabetes mellitus",
    "diyabet": "diabetes mellitus",
    "şeker hastalığı": "diabetes mellitus",
    "type 1 diabetes": "type 1 diabetes mellitus",
    "type 2 diabetes": "type 2 diabetes mellitus",
    "tip 1 diyabet": "type 1 diabetes mellitus",
    "tip 2 diyabet": "type 2 diabetes mellitus",
    "diabetic ketoacidosis": "diabetic ketoacidosis",
    "dka": "diabetic ketoacidosis",
    "diyabetik ketoasidoz": "diabetic ketoacidosis",
    "hhs": "hyperosmolar hyperglycemic state",
    "hyperosmolar hyperglycemic state": "hyperosmolar hyperglycemic state",
    "hypoglycemia": "hypoglycemia",
    "hypoglycaemia": "hypoglycemia",
    "hipoglisemi": "hypoglycemia",
    "hyperglycemia": "hyperglycemia",
    "hiperglisemi": "hyperglycemia",
    "thyroid storm": "thyroid storm",
    "tiroid fırtınası": "thyroid storm",
    "thyrotoxicosis": "thyrotoxicosis",
    "hyperthyroidism": "hyperthyroidism",
    "hipertiroidi": "hyperthyroidism",
    "graves disease": "Graves disease",
    "myxedema coma": "myxedema coma",
    "hypothyroidism": "hypothyroidism",
    "hipotiroidi": "hypothyroidism",
    "hashimoto": "Hashimoto thyroiditis",
    "adrenal crisis": "adrenal crisis",
    "addisonian crisis": "adrenal crisis",
    "addison krizi": "adrenal crisis",
    "adrenal insufficiency": "adrenal insufficiency",
    "addison disease": "Addison disease",
    "cushing syndrome": "Cushing syndrome",
    "cushing": "Cushing syndrome",
    "pheochromocytoma": "pheochromocytoma",
    "feokromositoma": "pheochromocytoma",
    "paraganglioma": "paraganglioma",
    "hyponatremia": "hyponatremia",
    "hiponatremi": "hyponatremia",
    "siadh": "syndrome of inappropriate ADH secretion",
    "hypernatremia": "hypernatremia",
    "hyperkalemia": "hyperkalemia",
    "hiperkalemi": "hyperkalemia",
    "hypokalemia": "hypokalemia",
    "hipokalemi": "hypokalemia",
    "hypercalcemia": "hypercalcemia",
    "hiperkalsemi": "hypercalcemia",
    "hypocalcemia": "hypocalcemia",
    "primary hyperparathyroidism": "primary hyperparathyroidism",
    "hypomagnesemia": "hypomagnesemia",

    # ── NUTRITION / VITAMINS ────────────────────────────────────
    "thiamine deficiency": "thiamine deficiency",
    "thiamine": "thiamine deficiency",
    "tiamin": "thiamine deficiency",
    "tiamin eksikliği": "thiamine deficiency",
    "vitamin b1": "thiamine deficiency",
    "b1 deficiency": "thiamine deficiency",
    "b1 eksikliği": "thiamine deficiency",
    "vitamin b12 deficiency": "vitamin B12 deficiency",
    "b12 deficiency": "vitamin B12 deficiency",
    "b12 eksikliği": "vitamin B12 deficiency",
    "cobalamin deficiency": "vitamin B12 deficiency",
    "subacute combined degeneration": "subacute combined degeneration",
    "folate deficiency": "folate deficiency",
    "folik asit eksikliği": "folate deficiency",
    "iron deficiency": "iron deficiency anemia",
    "demir eksikliği": "iron deficiency anemia",
    "vitamin d deficiency": "vitamin D deficiency",
    "scurvy": "scurvy",
    "pellagra": "pellagra",
    "beriberi": "beriberi",
    "malnutrition": "malnutrition",
    "malnütrisyon": "malnutrition",
    "malabsorption": "malabsorption syndrome",
    "malabsorpsiyon": "malabsorption syndrome",
    "kwashiorkor": "kwashiorkor",
    "marasmus": "marasmus",
    "refeeding syndrome": "refeeding syndrome",

    # ── SURGERY ─────────────────────────────────────────────────
    "bariatric surgery": "bariatric surgery",
    "bariatrik cerrahi": "bariatric surgery",
    "gastric bypass": "bariatric surgery",
    "gastrik bypass": "bariatric surgery",
    "gastric sleeve": "bariatric surgery",
    "sleeve gastrectomy": "bariatric surgery",
    "tüp mide": "bariatric surgery",
    "roux-en-y": "bariatric surgery",
    "roux en y": "bariatric surgery",
    "whipple procedure": "pancreaticoduodenectomy",
    "colectomy": "colectomy",
    "cholecystectomy": "cholecystectomy",
    "appendectomy": "appendectomy",
    "gastrectomy": "gastrectomy",

    # ── INFECTIOUS DISEASE ──────────────────────────────────────
    "sepsis": "sepsis",
    "septic shock": "septic shock",
    "septik şok": "septic shock",
    "sirs": "systemic inflammatory response syndrome",
    "bacteremia": "bacteremia",
    "bakteriyemi": "bacteremia",
    "malaria": "malaria",
    "sıtma": "malaria",
    "falciparum malaria": "falciparum malaria",
    "tuberculosis": "tuberculosis",
    "tb": "tuberculosis",
    "tbc": "tuberculosis",
    "tüberküloz": "tuberculosis",
    "verem": "tuberculosis",
    "pulmonary tuberculosis": "pulmonary tuberculosis",
    "miliary tuberculosis": "miliary tuberculosis",
    "hiv": "HIV infection",
    "aids": "acquired immunodeficiency syndrome",
    "dengue": "dengue",
    "dengue hemorrhagic fever": "dengue hemorrhagic fever",
    "typhoid": "typhoid fever",
    "typhoid fever": "typhoid fever",
    "tifo": "typhoid fever",
    "meningococcemia": "meningococcemia",
    "meningococcal disease": "meningococcal disease",
    "necrotizing fasciitis": "necrotizing fasciitis",
    "nekrotizan fasiit": "necrotizing fasciitis",
    "cellulitis": "cellulitis",
    "selülit": "cellulitis",
    "erysipelas": "erysipelas",
    "osteomyelitis": "osteomyelitis",
    "osteomiyelit": "osteomyelitis",
    "urinary tract infection": "urinary tract infection",
    "uti": "urinary tract infection",
    "idrar yolu enfeksiyonu": "urinary tract infection",
    "pyelonephritis": "pyelonephritis",
    "piyelonefrit": "pyelonephritis",
    "lyme disease": "Lyme disease",
    "borrelia": "Lyme disease",
    "leptospirosis": "leptospirosis",
    "leptospiroz": "leptospirosis",
    "rabies": "rabies",
    "kuduz": "rabies",
    "tetanus": "tetanus",
    "tetanoz": "tetanus",
    "anthrax": "anthrax",
    "şarbon": "anthrax",
    "brucellosis": "brucellosis",
    "bruselloz": "brucellosis",
    "toxoplasmosis": "toxoplasmosis",
    "toksoplazmoz": "toxoplasmosis",
    "pneumocystis": "Pneumocystis pneumonia",
    "pjp": "Pneumocystis pneumonia",
    "cmv": "cytomegalovirus infection",
    "cytomegalovirus": "cytomegalovirus infection",
    "ebv": "Epstein-Barr virus infection",
    "infectious mononucleosis": "infectious mononucleosis",
    "mononucleosis": "infectious mononucleosis",
    "covid": "COVID-19",
    "covid-19": "COVID-19",
    "sars-cov-2": "COVID-19",
    "influenza": "influenza",
    "grip": "influenza",
    "measles": "measles",
    "kızamık": "measles",
    "mumps": "mumps",
    "kabakulak": "mumps",
    "varicella": "varicella",
    "su çiçeği": "varicella",
    "herpes zoster": "herpes zoster",
    "zona": "herpes zoster",
    "hantavirus": "hantavirus infection",
    "lemierre": "Lemierre syndrome",
    "lemierre syndrome": "Lemierre syndrome",

    # ── HEMATOLOGY / ONCOLOGY ───────────────────────────────────
    "anemia": "anemia",
    "anaemia": "anemia",
    "anemi": "anemia",
    "iron deficiency anemia": "iron deficiency anemia",
    "hemolytic anemia": "hemolytic anemia",
    "autoimmune hemolytic anemia": "autoimmune hemolytic anemia",
    "sickle cell disease": "sickle cell disease",
    "orak hücreli anemi": "sickle cell disease",
    "sickle cell crisis": "sickle cell crisis",
    "thalassemia": "thalassemia",
    "talasemi": "thalassemia",
    "aplastic anemia": "aplastic anemia",
    "dic": "disseminated intravascular coagulation",
    "disseminated intravascular coagulation": "disseminated intravascular coagulation",
    "ttp": "thrombotic thrombocytopenic purpura",
    "thrombotic thrombocytopenic purpura": "thrombotic thrombocytopenic purpura",
    "hus": "hemolytic uremic syndrome",
    "hemolytic uremic syndrome": "hemolytic uremic syndrome",
    "pancytopenia": "pancytopenia",
    "pansitopeni": "pancytopenia",
    "thrombocytopenia": "thrombocytopenia",
    "trombositopeni": "thrombocytopenia",
    "neutropenic fever": "febrile neutropenia",
    "febrile neutropenia": "febrile neutropenia",
    "leukemia": "leukemia",
    "lösemi": "leukemia",
    "acute leukemia": "acute leukemia",
    # "all" removed — collides with common English word via substring match
    "aml": "acute myeloid leukemia",
    "cll": "chronic lymphocytic leukemia",
    "cml": "chronic myeloid leukemia",
    "lymphoma": "lymphoma",
    "lenfoma": "lymphoma",
    "hodgkin lymphoma": "Hodgkin lymphoma",
    "non-hodgkin lymphoma": "non-Hodgkin lymphoma",
    "multiple myeloma": "multiple myeloma",
    "myeloma": "multiple myeloma",
    "polycythemia vera": "polycythemia vera",
    "heparin induced thrombocytopenia": "heparin-induced thrombocytopenia",
    "hit": "heparin-induced thrombocytopenia",

    # ── NEPHROLOGY ──────────────────────────────────────────────
    "acute kidney injury": "acute kidney injury",
    "aki": "acute kidney injury",
    "akut böbrek hasarı": "acute kidney injury",
    "acute renal failure": "acute kidney injury",
    "chronic kidney disease": "chronic kidney disease",
    "ckd": "chronic kidney disease",
    "kronik böbrek hastalığı": "chronic kidney disease",
    "nephrotic syndrome": "nephrotic syndrome",
    "nefrotik sendrom": "nephrotic syndrome",
    "nephritic syndrome": "nephritic syndrome",
    "nefritik sendrom": "nephritic syndrome",
    "glomerulonephritis": "glomerulonephritis",
    "iga nephropathy": "IgA nephropathy",
    "rhabdomyolysis": "rhabdomyolysis",
    "rabdomiyoliz": "rhabdomyolysis",
    "myoglobinuria": "myoglobinuria",
    "nephrolithiasis": "nephrolithiasis",
    "kidney stone": "nephrolithiasis",
    "böbrek taşı": "nephrolithiasis",
    "renal calculus": "nephrolithiasis",
    "renal tubular acidosis": "renal tubular acidosis",
    "rta": "renal tubular acidosis",
    "dialysis": "dialysis",
    "diyaliz": "dialysis",

    # ── RHEUMATOLOGY ────────────────────────────────────────────
    "lupus": "systemic lupus erythematosus",
    "sle": "systemic lupus erythematosus",
    "systemic lupus erythematosus": "systemic lupus erythematosus",
    "lupus eritematozus": "systemic lupus erythematosus",
    "rheumatoid arthritis": "rheumatoid arthritis",
    "ra": "rheumatoid arthritis",
    "romatoid artrit": "rheumatoid arthritis",
    "gout": "gout",
    "gut": "gout",
    "gouty arthritis": "gout",
    "reactive arthritis": "reactive arthritis",
    "ankylosing spondylitis": "ankylosing spondylitis",
    # "as" removed — collides with common English word via substring match
    "polymyalgia rheumatica": "polymyalgia rheumatica",
    "giant cell arteritis": "giant cell arteritis",
    "temporal arteritis": "giant cell arteritis",
    "dermatomyositis": "dermatomyositis",
    "polymyositis": "polymyositis",
    "scleroderma": "systemic sclerosis",
    "systemic sclerosis": "systemic sclerosis",
    "skleroderma": "systemic sclerosis",
    "vasculitis": "vasculitis",
    "vaskülit": "vasculitis",
    "sarcoidosis": "sarcoidosis",
    "sarkoidoz": "sarcoidosis",
    "behcet disease": "Behcet disease",
    "behçet hastalığı": "Behcet disease",
    "kawasaki disease": "Kawasaki disease",
    "polyarteritis nodosa": "polyarteritis nodosa",
    "granulomatosis with polyangiitis": "granulomatosis with polyangiitis",
    "wegener": "granulomatosis with polyangiitis",
    "antiphospholipid syndrome": "antiphospholipid syndrome",
    "aps": "antiphospholipid syndrome",
    "fibromyalgia": "fibromyalgia",
    "fibromiyalji": "fibromyalgia",

    # ── PSYCHIATRY ──────────────────────────────────────────────
    "depression": "major depressive disorder",
    "depresyon": "major depressive disorder",
    "major depressive disorder": "major depressive disorder",
    "mdd": "major depressive disorder",
    "bipolar disorder": "bipolar disorder",
    "bipolar bozukluk": "bipolar disorder",
    "mania": "mania",
    "mani": "mania",
    "schizophrenia": "schizophrenia",
    "şizofreni": "schizophrenia",
    "acute psychosis": "acute psychosis",
    "panic disorder": "panic disorder",
    "anxiety": "anxiety disorder",
    "anksiyete": "anxiety disorder",
    "ocd": "obsessive-compulsive disorder",
    "obsessive compulsive disorder": "obsessive-compulsive disorder",
    "ptsd": "post-traumatic stress disorder",
    "post traumatic stress disorder": "post-traumatic stress disorder",
    "anorexia nervosa": "anorexia nervosa",
    "anoreksiya nervoza": "anorexia nervosa",
    "bulimia": "bulimia nervosa",
    "suicidal ideation": "suicidal ideation",
    "intihar düşüncesi": "suicidal ideation",

    # ── OBSTETRICS / GYNECOLOGY ─────────────────────────────────
    "ectopic pregnancy": "ectopic pregnancy",
    "ektopik gebelik": "ectopic pregnancy",
    "dış gebelik": "ectopic pregnancy",
    "preeclampsia": "preeclampsia",
    "preeklampsi": "preeclampsia",
    "eclampsia": "eclampsia",
    "eklampsi": "eclampsia",
    "hellp syndrome": "HELLP syndrome",
    "hellp": "HELLP syndrome",
    "placental abruption": "placental abruption",
    "plasenta dekolmanı": "placental abruption",
    "placenta previa": "placenta previa",
    "gestational diabetes": "gestational diabetes",
    "gestasyonel diyabet": "gestational diabetes",
    "postpartum hemorrhage": "postpartum hemorrhage",
    "ovarian torsion": "ovarian torsion",
    "over torsiyonu": "ovarian torsion",
    "pelvic inflammatory disease": "pelvic inflammatory disease",
    "pid": "pelvic inflammatory disease",
    "hyperemesis gravidarum": "hyperemesis gravidarum",

    # ── TOXICOLOGY ──────────────────────────────────────────────
    "acetaminophen overdose": "acetaminophen overdose",
    "paracetamol overdose": "acetaminophen overdose",
    "parasetamol zehirlenmesi": "acetaminophen overdose",
    "opioid overdose": "opioid overdose",
    "naloxone": "naloxone",
    "benzodiazepine overdose": "benzodiazepine overdose",
    "flumazenil": "flumazenil",
    "organophosphate poisoning": "organophosphate poisoning",
    "organofosfat zehirlenmesi": "organophosphate poisoning",
    "cholinergic crisis": "cholinergic crisis",
    "anticholinergic toxicity": "anticholinergic toxicity",
    "serotonin syndrome": "serotonin syndrome",
    "serotonin sendromu": "serotonin syndrome",
    "neuroleptic malignant syndrome": "neuroleptic malignant syndrome",
    "nms": "neuroleptic malignant syndrome",
    "malignant hyperthermia": "malignant hyperthermia",
    "carbon monoxide poisoning": "carbon monoxide poisoning",
    "karbon monoksit zehirlenmesi": "carbon monoxide poisoning",
    "cyanide poisoning": "cyanide poisoning",
    "alcohol withdrawal": "alcohol withdrawal syndrome",
    "alkol yoksunluğu": "alcohol withdrawal syndrome",
    "delirium tremens": "delirium tremens",
    "methanol poisoning": "methanol poisoning",
    "ethylene glycol poisoning": "ethylene glycol poisoning",
    "salicylate toxicity": "salicylate toxicity",
    "lithium toxicity": "lithium toxicity",
    "digoxin toxicity": "digoxin toxicity",
    "warfarin overdose": "warfarin overdose",
    "iron poisoning": "iron poisoning",
    "lead poisoning": "lead poisoning",
    "kurşun zehirlenmesi": "lead poisoning",
    "arsenic poisoning": "arsenic poisoning",
    # Extended toxicology coverage
    "methyl salicylate": "methyl salicylate toxicity",
    "wintergreen oil": "methyl salicylate toxicity",
    "wintergreen": "methyl salicylate toxicity",
    "oil of wintergreen": "methyl salicylate toxicity",
    "keklik üzümü yağı": "methyl salicylate toxicity",
    "pelesenk yağı": "methyl salicylate toxicity",
    "pelesenk": "methyl salicylate toxicity",
    "salicylate poisoning": "salicylate toxicity",
    "salisilat zehirlenmesi": "salicylate toxicity",
    "aspirin poisoning": "salicylate toxicity",
    "aspirin overdose": "salicylate toxicity",
    "salicylism": "salicylate toxicity",
    "methanol": "methanol poisoning",
    "metanol zehirlenmesi": "methanol poisoning",
    "ethylene glycol": "ethylene glycol poisoning",
    "antifriz zehirlenmesi": "ethylene glycol poisoning",
    "cyanide": "cyanide poisoning",
    "siyanür zehirlenmesi": "cyanide poisoning",
    "hydrogen sulfide": "hydrogen sulfide poisoning",
    "hydrogen cyanide": "cyanide poisoning",
    "carbon monoxide": "carbon monoxide poisoning",
    "arsenic": "arsenic poisoning",
    "arsenik zehirlenmesi": "arsenic poisoning",
    "mercury poisoning": "mercury poisoning",
    "civa zehirlenmesi": "mercury poisoning",
    "thallium poisoning": "thallium poisoning",
    "iron overdose": "iron poisoning",
    "demir zehirlenmesi": "iron poisoning",
    "beta blocker overdose": "beta blocker toxicity",
    "calcium channel blocker overdose": "calcium channel blocker toxicity",
    "tricyclic antidepressant overdose": "tricyclic antidepressant toxicity",
    "tca overdose": "tricyclic antidepressant toxicity",
    "ssri overdose": "SSRI toxicity",
    "strychnine poisoning": "strychnine poisoning",
    "mushroom poisoning": "mushroom poisoning",
    "mantar zehirlenmesi": "mushroom poisoning",
    "snake bite": "snake envenomation",
    "yılan ısırığı": "snake envenomation",
    "scorpion sting": "scorpion envenomation",
    "akrep sokması": "scorpion envenomation",
    "methemoglobinemia": "methemoglobinemia",
    "methemoglobin": "methemoglobinemia",

    # ── EMERGENCY / TRAUMA ──────────────────────────────────────
    "anaphylaxis": "anaphylaxis",
    "anafilaksi": "anaphylaxis",
    "anaphylactic shock": "anaphylactic shock",
    "cardiac arrest": "cardiac arrest",
    "kardiyak arrest": "cardiac arrest",
    "burn": "burns",
    "yanık": "burns",
    "hypothermia": "hypothermia",
    "hipotermi": "hypothermia",
    "hyperthermia": "hyperthermia",
    "heat stroke": "heat stroke",
    "sıcak çarpması": "heat stroke",
    "drowning": "drowning",
    "boğulma": "drowning",
    "electrical injury": "electrical injury",
    "compartment syndrome": "compartment syndrome",
    "crush syndrome": "crush syndrome",
    "fat embolism": "fat embolism syndrome",

    # ── TUMORS / CYSTS ──────────────────────────────────────────
    "dermoid cyst": "ovarian teratoma",
    "dermoid": "teratoma",
    "teratoma": "teratoma",
    "ovarian teratoma": "ovarian teratoma",
    "ovarian cyst": "ovarian cyst",
    "brain tumor": "brain neoplasm",
    "beyin tümörü": "brain neoplasm",
    "glioblastoma": "glioblastoma",
    "meningioma": "meningioma",
    "pituitary adenoma": "pituitary adenoma",

    # ── GENERAL SYMPTOMS ────────────────────────────────────────
    "fever": "fever",
    "ateş": "fever",
    "cough": "cough",
    "öksürük": "cough",
    "chest pain": "chest pain",
    "göğüs ağrısı": "chest pain",
    "headache": "headache",
    "baş ağrısı": "headache",
    "back pain": "back pain",
    "bel ağrısı": "back pain",
    "rash": "skin rash",
    "döküntü": "skin rash",
    "edema": "edema",
    "ödem": "edema",
    "fatigue": "fatigue",
    "yorgunluk": "fatigue",
    "weight loss": "weight loss",
    "kilo kaybı": "weight loss",
    "weight gain": "weight gain",
    "kilo alımı": "weight gain",
    "syncope": "syncope",
    "senkop": "syncope",
    "palpitations": "palpitations",
    "çarpıntı": "palpitations",
    "diaphoresis": "diaphoresis",
    "terleme": "diaphoresis",
    "lymphadenopathy": "lymphadenopathy",
    "lenfadenopati": "lymphadenopathy",
    "splenomegaly": "splenomegaly",
    "splenomegali": "splenomegaly",
    "hepatomegaly": "hepatomegaly",
    "hepatomegali": "hepatomegaly",
    "petechiae": "petechiae",
    "peteşi": "petechiae",
    "purpura": "purpura",
    "ecchymosis": "ecchymosis",
    "arthralgia": "arthralgia",
    "artralji": "arthralgia",
    "myalgia": "myalgia",
    "kas ağrısı": "myalgia",
    "tremor": "tremor",
    "rigidity": "rigidity",
    "clonus": "clonus",
    "hyperreflexia": "hyperreflexia",
    "hyporeflexia": "hyporeflexia",
    "weakness": "muscle weakness",
    "güçsüzlük": "muscle weakness",
    "paralysis": "paralysis",
    "felç": "paralysis",
    "numbness": "numbness",
    "uyuşma": "numbness",
    "paresthesia": "paresthesia",
    "oliguria": "oliguria",
    "anuria": "anuria",
    "polyuria": "polyuria",
    "polydipsia": "polydipsia",
    "hematuria": "hematuria",
    "hematüri": "hematuria",
    "proteinuria": "proteinuria",
    "tinnitus": "tinnitus",
    "çınlama": "tinnitus",
    "photophobia": "photophobia",
    "neck stiffness": "neck stiffness",
    "ense sertliği": "neck stiffness",
    "nuchal rigidity": "nuchal rigidity",
}


# ═══════════════════════════════════════════════════════════════════════════
# CLINICAL LINKS — Symptom/sign co-occurrence → diagnostic association.
# When ALL trigger words appear in a query, the injection term is added.
#
# Format: ({trigger_words}, "injection_term")
# Organized by clinical reasoning pattern, not by specific disease.
# ═══════════════════════════════════════════════════════════════════════════

CLINICAL_LINKS: list[tuple[set[str], str]] = [

    # ── CARDIAC EMERGENCIES ─────────────────────────────────────
    ({"chest", "pain", "radiation"}, "acute coronary syndrome myocardial infarction"),
    ({"chest", "pain", "diaphoresis"}, "acute coronary syndrome"),
    ({"chest", "pain", "dyspnea"}, "pulmonary embolism acute coronary syndrome"),
    ({"chest", "tearing", "pain"}, "aortic dissection"),
    ({"hypotension", "distended", "muffled"}, "cardiac tamponade"),
    ({"dyspnea", "orthopnea", "edema"}, "heart failure"),
    ({"palpitations", "syncope"}, "arrhythmia"),
    ({"chest", "pain", "exertion"}, "angina acute coronary syndrome"),

    # ── ENDOCARDITIS PATTERNS ───────────────────────────────────
    ({"fever", "murmur"}, "infective endocarditis"),
    ({"fever", "murmur", "petechiae"}, "infective endocarditis"),
    ({"fever", "murmur", "splinter"}, "infective endocarditis"),
    ({"janeway", "osler"}, "infective endocarditis"),
    ({"dental", "fever", "murmur"}, "infective endocarditis bacteremia"),
    ({"prosthetic", "valve", "fever"}, "prosthetic valve endocarditis"),
    ({"iv", "drug", "fever"}, "infective endocarditis"),
    ({"fever", "emboli"}, "infective endocarditis"),

    # ── VENOUS THROMBOEMBOLISM ──────────────────────────────────
    ({"hemoptysis", "pleuritic"}, "pulmonary embolism"),
    ({"hemoptysis", "dyspnea", "tachycardia"}, "pulmonary embolism"),
    ({"unilateral", "leg", "swelling"}, "deep vein thrombosis"),
    ({"immobilization", "dyspnea"}, "pulmonary embolism"),
    ({"surgery", "dyspnea", "tachycardia"}, "pulmonary embolism"),
    ({"oral", "contraceptive", "headache"}, "cerebral venous thrombosis"),

    # ── NEUROLOGICAL EMERGENCIES ────────────────────────────────
    # Meningitis / Encephalitis
    ({"fever", "stiffness", "headache"}, "meningitis"),
    ({"fever", "neck", "photophobia"}, "meningitis"),
    ({"fever", "confusion", "seizure"}, "encephalitis"),
    ({"fever", "altered", "mental"}, "encephalitis meningitis"),
    ({"fever", "petechiae", "stiffness"}, "meningococcemia meningitis"),
    ({"headache", "papilledema"}, "intracranial hypertension"),

    # Stroke / Hemorrhage
    ({"thunderclap", "headache"}, "subarachnoid hemorrhage"),
    ({"worst", "headache"}, "subarachnoid hemorrhage"),
    ({"sudden", "headache", "stiffness"}, "subarachnoid hemorrhage"),
    ({"hemiparesis", "aphasia"}, "stroke"),
    ({"sudden", "weakness", "speech"}, "stroke"),
    ({"vision", "loss", "claudication"}, "giant cell arteritis"),
    ({"temporal", "headache", "claudication"}, "giant cell arteritis"),
    ({"headache", "jaw", "claudication"}, "giant cell arteritis"),
    ({"young", "stroke"}, "patent foramen ovale paradoxical embolism"),

    # Autoimmune / Paraneoplastic
    ({"teratoma", "encephalitis"}, "anti-NMDA receptor"),
    ({"teratoma", "psychosis"}, "anti-NMDA receptor"),
    ({"teratoma", "seizure"}, "anti-NMDA receptor paraneoplastic"),
    ({"dermoid", "encephalitis"}, "anti-NMDA receptor"),
    ({"dermoid", "psychosis"}, "anti-NMDA receptor"),
    ({"dermoid", "seizure"}, "anti-NMDA receptor paraneoplastic"),
    ({"ovarian", "encephalitis"}, "anti-NMDA receptor"),
    ({"ovarian", "psychosis"}, "anti-NMDA receptor"),
    ({"catatonia", "teratoma"}, "anti-NMDA receptor"),
    ({"catatonia", "ovarian"}, "anti-NMDA receptor"),
    ({"catatonia", "seizure"}, "autoimmune encephalitis"),
    ({"psychosis", "seizure", "fever"}, "autoimmune encephalitis"),
    ({"autonomic", "psychosis"}, "autoimmune encephalitis"),
    ({"autonomic", "seizure"}, "encephalitis"),

    # Motor / Neuromuscular
    ({"ascending", "weakness"}, "Guillain-Barre syndrome"),
    ({"ascending", "paralysis"}, "Guillain-Barre syndrome"),
    ({"descending", "paralysis"}, "botulism"),
    ({"descending", "weakness"}, "botulism"),
    ({"ptosis", "dysphagia"}, "myasthenia gravis botulism"),
    ({"fatigable", "weakness"}, "myasthenia gravis"),
    ({"food", "paralysis"}, "botulism"),

    # Nutritional Neurology (generic — not disease-specific)
    ({"bariatric", "encephalopathy"}, "nutritional deficiency Wernicke thiamine"),
    ({"bariatric", "confusion"}, "nutritional deficiency thiamine Wernicke"),
    ({"bariatric", "ataxia"}, "nutritional deficiency thiamine Wernicke"),
    ({"bariatric", "nystagmus"}, "Wernicke encephalopathy"),
    ({"bariatric", "ophthalmoplegia"}, "Wernicke encephalopathy"),
    ({"bariatric", "neuropathy"}, "vitamin B12 deficiency thiamine deficiency"),
    ({"bariatric", "anemia"}, "iron deficiency vitamin B12 deficiency"),
    ({"malnutrition", "confusion"}, "thiamine deficiency Wernicke"),
    ({"malnutrition", "ataxia"}, "thiamine deficiency Wernicke"),
    ({"malnutrition", "neuropathy"}, "vitamin B12 deficiency thiamine"),
    ({"malabsorption", "encephalopathy"}, "thiamine deficiency Wernicke"),
    ({"malabsorption", "confusion"}, "thiamine deficiency Wernicke"),
    ({"malabsorption", "neuropathy"}, "vitamin B12 deficiency"),
    ({"vomiting", "confusion", "ataxia"}, "Wernicke encephalopathy"),
    ({"vomiting", "ophthalmoplegia"}, "Wernicke encephalopathy thiamine"),
    ({"alcoholism", "confusion", "ataxia"}, "Wernicke encephalopathy"),
    ({"alcoholism", "neuropathy"}, "alcoholic neuropathy thiamine deficiency"),
    ({"starvation", "confusion"}, "refeeding syndrome thiamine deficiency"),
    ({"hyperemesis", "confusion"}, "Wernicke encephalopathy thiamine"),
    ({"hyperemesis", "ataxia"}, "Wernicke encephalopathy thiamine"),
    # Classic triads
    ({"ophthalmoplegia", "ataxia"}, "Wernicke encephalopathy"),
    ({"nystagmus", "ataxia", "confusion"}, "Wernicke encephalopathy"),
    ({"ophthalmoplegia", "confusion"}, "Wernicke encephalopathy"),
    ({"nystagmus", "ataxia"}, "Wernicke encephalopathy thiamine"),
    # Cofactor safety
    ({"thiamine", "glucose"}, "thiamine before glucose refeeding"),
    ({"thiamine", "hypoglycemia"}, "thiamine before glucose Wernicke"),

    # ── GASTROINTESTINAL EMERGENCIES ────────────────────────────
    ({"rlq", "pain", "fever"}, "appendicitis"),
    ({"right", "lower", "quadrant", "fever"}, "appendicitis"),
    ({"ruq", "pain", "fever", "jaundice"}, "ascending cholangitis"),
    ({"right", "upper", "quadrant", "fever"}, "cholecystitis cholangitis"),
    ({"epigastric", "pain", "vomiting"}, "pancreatitis"),
    ({"epigastric", "pain", "lipase"}, "acute pancreatitis"),
    ({"bloody", "diarrhea", "fever"}, "inflammatory bowel disease infectious colitis"),
    ({"distension", "vomiting", "constipation"}, "bowel obstruction"),
    ({"melena", "hematemesis"}, "upper gastrointestinal hemorrhage"),
    ({"painless", "jaundice"}, "pancreatic cancer cholangiocarcinoma"),
    ({"abdominal", "pain", "jaundice", "fever"}, "cholangitis"),
    ({"spider", "nevi", "ascites"}, "liver cirrhosis"),
    ({"ascites", "jaundice"}, "liver cirrhosis hepatic failure"),

    # ── ENDOCRINE EMERGENCIES ───────────────────────────────────
    ({"polyuria", "polydipsia", "weight"}, "diabetes mellitus"),
    ({"kussmaul", "hyperglycemia"}, "diabetic ketoacidosis"),
    ({"hyperglycemia", "acidosis"}, "diabetic ketoacidosis"),
    ({"altered", "hypoglycemia"}, "hypoglycemia insulin overdose"),
    ({"weight", "loss", "tachycardia", "tremor"}, "thyrotoxicosis hyperthyroidism"),
    ({"exophthalmos", "goiter"}, "Graves disease"),
    ({"hypotension", "hypoglycemia", "confusion"}, "adrenal crisis"),
    ({"hypotension", "hyperkalemia"}, "adrenal crisis"),
    ({"hypertension", "headache", "diaphoresis", "palpitations"}, "pheochromocytoma"),
    ({"paroxysmal", "hypertension"}, "pheochromocytoma"),
    ({"obesity", "striae", "moon"}, "Cushing syndrome"),

    # ── INFECTIOUS DISEASE PATTERNS ─────────────────────────────
    ({"fever", "night", "sweats", "weight"}, "tuberculosis lymphoma"),
    ({"cough", "hemoptysis", "night"}, "tuberculosis"),
    ({"travel", "fever", "splenomegaly"}, "malaria"),
    ({"travel", "fever", "jaundice"}, "malaria hepatitis leptospirosis"),
    ({"travel", "diarrhea", "fever"}, "typhoid traveler diarrhea"),
    ({"animal", "bite", "hydrophobia"}, "rabies"),
    ({"wound", "trismus", "spasms"}, "tetanus"),
    ({"cat", "scratch", "lymphadenopathy"}, "cat scratch disease Bartonella"),
    ({"rodent", "fever", "renal"}, "hantavirus hemorrhagic fever"),
    ({"cave", "bat", "pulmonary"}, "histoplasmosis"),
    ({"tick", "rash", "arthralgia"}, "Lyme disease"),
    ({"tick", "erythema", "migrans"}, "Lyme disease"),
    ({"immunocompromised", "pneumonia"}, "Pneumocystis opportunistic infection"),
    ({"transplant", "fever"}, "opportunistic infection CMV"),
    ({"fever", "jaundice", "renal"}, "leptospirosis hepatorenal"),
    ({"fever", "lymphadenopathy", "weight"}, "lymphoma HIV tuberculosis"),
    ({"fever", "rash", "arthralgia"}, "dengue chikungunya viral exanthem"),

    # ── HEMATOLOGIC EMERGENCIES ─────────────────────────────────
    ({"petechiae", "thrombocytopenia", "renal"}, "TTP HUS"),
    ({"microangiopathic", "hemolysis"}, "TTP HUS DIC"),
    ({"sickle", "cell", "pain"}, "sickle cell vaso-occlusive crisis"),
    ({"pancytopenia", "fever"}, "aplastic anemia leukemia"),
    ({"bleeding", "thrombocytopenia"}, "DIC TTP ITP"),

    # ── RENAL PATTERNS ──────────────────────────────────────────
    ({"dark", "urine", "muscle"}, "rhabdomyolysis myoglobinuria"),
    ({"edema", "proteinuria"}, "nephrotic syndrome"),
    ({"hematuria", "hypertension", "edema"}, "nephritic syndrome glomerulonephritis"),
    ({"flank", "pain", "hematuria"}, "nephrolithiasis renal calculus"),
    ({"oliguria", "elevated", "creatinine"}, "acute kidney injury"),

    # ── RHEUMATOLOGIC PATTERNS ──────────────────────────────────
    ({"butterfly", "rash", "arthralgia"}, "systemic lupus erythematosus"),
    ({"malar", "rash", "arthritis"}, "systemic lupus erythematosus"),
    ({"alopecia", "oral", "ulcers"}, "systemic lupus erythematosus"),
    ({"morning", "stiffness", "polyarthritis"}, "rheumatoid arthritis"),
    ({"monoarthritis", "podagra"}, "gout"),
    ({"acute", "monoarthritis", "crystals"}, "gout pseudogout"),
    ({"proximal", "weakness", "rash"}, "dermatomyositis polymyositis"),
    ({"raynaud", "skin", "thickening"}, "systemic sclerosis scleroderma"),
    ({"oral", "genital", "ulcer"}, "Behcet disease"),
    ({"purpura", "abdominal", "arthritis"}, "IgA vasculitis Henoch-Schonlein"),
    ({"saddle", "nose"}, "granulomatosis with polyangiitis"),

    # ── TOXICOLOGY PATTERNS ─────────────────────────────────────
    ({"miosis", "bradycardia", "secretions"}, "organophosphate poisoning cholinergic"),
    ({"mydriasis", "tachycardia", "dry"}, "anticholinergic toxicity"),
    ({"respiratory", "depression", "miosis"}, "opioid overdose"),
    ({"clonus", "tremor", "hyperthermia"}, "serotonin syndrome"),
    ({"rigidity", "hyperthermia", "altered"}, "neuroleptic malignant syndrome"),
    ({"cherry", "red"}, "carbon monoxide poisoning"),
    ({"gap", "acidosis", "osmolar"}, "toxic alcohol methanol ethylene glycol"),
    # Extended toxicology patterns
    ({"tinnitus", "hyperventilation"}, "salicylate toxicity aspirin poisoning"),
    ({"tinnitus", "fever", "hyperventilation"}, "salicylate poisoning"),
    ({"tinnitus", "acidosis"}, "salicylate toxicity"),
    ({"tinnitus", "ingestion"}, "salicylate toxicity drug toxicity"),
    ({"wintergreen", "tinnitus"}, "methyl salicylate toxicity"),
    ({"salicylate", "acidosis"}, "salicylate poisoning treatment"),
    ({"methanol", "vision"}, "methanol poisoning fomepizole"),
    ({"antifreeze", "acidosis"}, "ethylene glycol poisoning"),
    ({"garlic", "breath"}, "organophosphate arsenic selenium poisoning"),
    ({"blue", "cyanosis", "normal"}, "methemoglobinemia"),
    ({"chocolate", "colored", "blood"}, "methemoglobinemia"),
    ({"cyanosis", "oxygen"}, "methemoglobinemia carbon monoxide"),
    ({"almond", "smell"}, "cyanide poisoning"),
    ({"seizure", "ingestion"}, "drug toxicity poisoning"),
    ({"metabolic", "acidosis", "ingestion"}, "toxic ingestion poisoning"),

    # ── OB/GYN EMERGENCIES ──────────────────────────────────────
    ({"amenorrhea", "abdominal", "bleeding"}, "ectopic pregnancy"),
    ({"positive", "pregnancy", "pain"}, "ectopic pregnancy"),
    ({"hypertension", "proteinuria", "pregnancy"}, "preeclampsia"),
    ({"seizure", "pregnancy"}, "eclampsia"),
    ({"hemolysis", "liver", "platelets"}, "HELLP syndrome"),
    ({"postpartum", "bleeding"}, "postpartum hemorrhage"),
    ({"acute", "pelvic", "pain"}, "ovarian torsion ectopic pregnancy"),
]


# ═══════════════════════════════════════════════════════════════════════════
# PUBMED MESH — Maps common medical terms to official MeSH descriptor names.
# Used by _optimize_pubmed_query() to wrap terms in "Term"[MeSH] syntax.
#
# Format: "lowercase_input" → "Official MeSH Heading"
# Searched longest-match-first to handle multi-word terms correctly.
# ═══════════════════════════════════════════════════════════════════════════

PUBMED_MESH: dict[str, str] = {

    # ── CARDIOLOGY ──────────────────────────────────────────────
    "myocardial infarction": "Myocardial Infarction",
    "acute coronary syndrome": "Acute Coronary Syndrome",
    "heart failure": "Heart Failure",
    "congestive heart failure": "Heart Failure",
    "atrial fibrillation": "Atrial Fibrillation",
    "ventricular tachycardia": "Tachycardia, Ventricular",
    "aortic dissection": "Aortic Dissection",
    "aortic aneurysm": "Aortic Aneurysm",
    "cardiac tamponade": "Cardiac Tamponade",
    "pericarditis": "Pericarditis",
    "pericardial effusion": "Pericardial Effusion",
    "myocarditis": "Myocarditis",
    "endocarditis": "Endocarditis",
    "infective endocarditis": "Endocarditis, Bacterial",
    "cardiomyopathy": "Cardiomyopathies",
    "dilated cardiomyopathy": "Cardiomyopathy, Dilated",
    "hypertrophic cardiomyopathy": "Cardiomyopathy, Hypertrophic",
    "deep vein thrombosis": "Venous Thrombosis",
    "pulmonary embolism": "Pulmonary Embolism",
    "venous thromboembolism": "Venous Thromboembolism",
    "hypertension": "Hypertension",
    "hypertensive crisis": "Hypertensive Emergency",
    "arrhythmia": "Arrhythmias, Cardiac",

    # ── PULMONOLOGY ─────────────────────────────────────────────
    "pneumonia": "Pneumonia",
    "community-acquired pneumonia": "Community-Acquired Infections",
    "aspiration pneumonia": "Pneumonia, Aspiration",
    "chronic obstructive pulmonary disease": "Pulmonary Disease, Chronic Obstructive",
    "copd": "Pulmonary Disease, Chronic Obstructive",
    "asthma": "Asthma",
    "status asthmaticus": "Status Asthmaticus",
    "pneumothorax": "Pneumothorax",
    "tension pneumothorax": "Pneumothorax",
    "acute respiratory distress syndrome": "Respiratory Distress Syndrome",
    "ards": "Respiratory Distress Syndrome",
    "pleural effusion": "Pleural Effusion",
    "empyema": "Empyema",
    "pulmonary fibrosis": "Pulmonary Fibrosis",
    "interstitial lung disease": "Lung Diseases, Interstitial",
    "lung cancer": "Lung Neoplasms",
    "hemoptysis": "Hemoptysis",
    "respiratory failure": "Respiratory Insufficiency",

    # ── NEUROLOGY ───────────────────────────────────────────────
    "stroke": "Stroke",
    "ischemic stroke": "Ischemic Stroke",
    "hemorrhagic stroke": "Hemorrhagic Stroke",
    "transient ischemic attack": "Ischemic Attack, Transient",
    "subarachnoid hemorrhage": "Subarachnoid Hemorrhage",
    "intracerebral hemorrhage": "Cerebral Hemorrhage",
    "subdural hematoma": "Hematoma, Subdural",
    "epidural hematoma": "Hematoma, Epidural, Cranial",
    "meningitis": "Meningitis",
    "bacterial meningitis": "Meningitis, Bacterial",
    "viral meningitis": "Meningitis, Viral",
    "encephalitis": "Encephalitis",
    "herpes simplex encephalitis": "Encephalitis, Herpes Simplex",
    "autoimmune encephalitis": "Autoimmune Encephalitis",
    "anti-nmda receptor encephalitis": "Anti-N-Methyl-D-Aspartate Receptor Encephalitis",
    "paraneoplastic syndrome": "Paraneoplastic Syndromes",
    "encephalopathy": "Brain Diseases",
    "wernicke encephalopathy": "Wernicke Encephalopathy",
    "korsakoff syndrome": "Korsakoff Syndrome",
    "hepatic encephalopathy": "Hepatic Encephalopathy",
    "seizures": "Seizures",
    "seizure": "Seizures",
    "epilepsy": "Epilepsy",
    "status epilepticus": "Status Epilepticus",
    "guillain-barre syndrome": "Guillain-Barre Syndrome",
    "guillain-barre": "Guillain-Barre Syndrome",
    "multiple sclerosis": "Multiple Sclerosis",
    "migraine": "Migraine Disorders",
    "parkinson disease": "Parkinson Disease",
    "amyotrophic lateral sclerosis": "Amyotrophic Lateral Sclerosis",
    "brain abscess": "Brain Abscess",
    "normal pressure hydrocephalus": "Hydrocephalus, Normal Pressure",
    "cerebral venous thrombosis": "Intracranial Thrombosis",
    "myasthenia gravis": "Myasthenia Gravis",
    "catatonia": "Catatonia",
    "delirium": "Delirium",
    "nystagmus": "Nystagmus, Pathologic",
    "ophthalmoplegia": "Ophthalmoplegia",
    "diplopia": "Diplopia",
    "ataxia": "Ataxia",
    "confusion": "Confusion",
    "vertigo": "Vertigo",
    "peripheral neuropathy": "Peripheral Nervous System Diseases",
    "bell palsy": "Bell Palsy",
    "trigeminal neuralgia": "Trigeminal Neuralgia",

    # ── GASTROENTEROLOGY ────────────────────────────────────────
    "appendicitis": "Appendicitis",
    "pancreatitis": "Pancreatitis",
    "acute pancreatitis": "Pancreatitis",
    "cholecystitis": "Cholecystitis",
    "cholelithiasis": "Cholelithiasis",
    "choledocholithiasis": "Choledocholithiasis",
    "cholangitis": "Cholangitis",
    "gastrointestinal hemorrhage": "Gastrointestinal Hemorrhage",
    "intestinal obstruction": "Intestinal Obstruction",
    "peptic ulcer": "Peptic Ulcer",
    "inflammatory bowel disease": "Inflammatory Bowel Diseases",
    "crohn disease": "Crohn Disease",
    "ulcerative colitis": "Colitis, Ulcerative",
    "diverticulitis": "Diverticulitis",
    "hepatitis": "Hepatitis",
    "hepatitis a": "Hepatitis A",
    "hepatitis b": "Hepatitis B",
    "hepatitis c": "Hepatitis C",
    "liver cirrhosis": "Liver Cirrhosis",
    "liver failure": "Liver Failure",
    "celiac disease": "Celiac Disease",
    "esophageal varices": "Esophageal and Gastric Varices",
    "ascites": "Ascites",

    # ── ENDOCRINOLOGY ───────────────────────────────────────────
    "diabetes mellitus": "Diabetes Mellitus",
    "type 1 diabetes": "Diabetes Mellitus, Type 1",
    "type 2 diabetes": "Diabetes Mellitus, Type 2",
    "diabetic ketoacidosis": "Diabetic Ketoacidosis",
    "hypoglycemia": "Hypoglycemia",
    "hyperglycemia": "Hyperglycemia",
    "thyroid storm": "Thyroid Crisis",
    "hyperthyroidism": "Hyperthyroidism",
    "graves disease": "Graves Disease",
    "hypothyroidism": "Hypothyroidism",
    "myxedema coma": "Myxedema",
    "adrenal crisis": "Adrenal Insufficiency",
    "adrenal insufficiency": "Adrenal Insufficiency",
    "addison disease": "Addison Disease",
    "cushing syndrome": "Cushing Syndrome",
    "pheochromocytoma": "Pheochromocytoma",
    "hyponatremia": "Hyponatremia",
    "hypernatremia": "Hypernatremia",
    "hyperkalemia": "Hyperkalemia",
    "hypokalemia": "Hypokalemia",
    "hypercalcemia": "Hypercalcemia",
    "hypocalcemia": "Hypocalcemia",

    # ── NUTRITION / VITAMINS ────────────────────────────────────
    "thiamine deficiency": "Thiamine Deficiency",
    "thiamine": "Thiamine",
    "vitamin b12 deficiency": "Vitamin B 12 Deficiency",
    "folate deficiency": "Folic Acid Deficiency",
    "iron deficiency anemia": "Anemia, Iron-Deficiency",
    "malnutrition": "Malnutrition",
    "malabsorption": "Malabsorption Syndromes",
    "beriberi": "Beriberi",
    "pellagra": "Pellagra",
    "scurvy": "Scurvy",
    "refeeding syndrome": "Refeeding Syndrome",

    # ── SURGERY ─────────────────────────────────────────────────
    "bariatric surgery": "Bariatric Surgery",
    "gastric bypass": "Gastric Bypass",
    "gastrectomy": "Gastrectomy",

    # ── INFECTIOUS DISEASE ──────────────────────────────────────
    "sepsis": "Sepsis",
    "septic shock": "Shock, Septic",
    "malaria": "Malaria",
    "tuberculosis": "Tuberculosis",
    "pulmonary tuberculosis": "Tuberculosis, Pulmonary",
    "miliary tuberculosis": "Tuberculosis, Miliary",
    "hiv": "HIV Infections",
    "aids": "Acquired Immunodeficiency Syndrome",
    "dengue": "Dengue",
    "typhoid fever": "Typhoid Fever",
    "meningococcemia": "Meningococcemia",
    "necrotizing fasciitis": "Fasciitis, Necrotizing",
    "osteomyelitis": "Osteomyelitis",
    "urinary tract infection": "Urinary Tract Infections",
    "pyelonephritis": "Pyelonephritis",
    "lyme disease": "Lyme Disease",
    "leptospirosis": "Leptospirosis",
    "rabies": "Rabies",
    "tetanus": "Tetanus",
    "anthrax": "Anthrax",
    "brucellosis": "Brucellosis",
    "toxoplasmosis": "Toxoplasmosis",
    "covid-19": "COVID-19",
    "influenza": "Influenza, Human",
    "hantavirus": "Hantavirus Infections",
    "botulism": "Botulism",
    "lemierre syndrome": "Lemierre Syndrome",
    "pneumocystis pneumonia": "Pneumonia, Pneumocystis",
    "cellulitis": "Cellulitis",

    # ── HEMATOLOGY / ONCOLOGY ───────────────────────────────────
    "anemia": "Anemia",
    "hemolytic anemia": "Anemia, Hemolytic",
    "sickle cell disease": "Anemia, Sickle Cell",
    "thalassemia": "Thalassemia",
    "aplastic anemia": "Anemia, Aplastic",
    "disseminated intravascular coagulation": "Disseminated Intravascular Coagulation",
    "thrombotic thrombocytopenic purpura": "Purpura, Thrombotic Thrombocytopenic",
    "hemolytic uremic syndrome": "Hemolytic-Uremic Syndrome",
    "thrombocytopenia": "Thrombocytopenia",
    "febrile neutropenia": "Febrile Neutropenia",
    "leukemia": "Leukemia",
    "lymphoma": "Lymphoma",
    "hodgkin lymphoma": "Hodgkin Disease",
    "non-hodgkin lymphoma": "Lymphoma, Non-Hodgkin",
    "multiple myeloma": "Multiple Myeloma",
    "heparin-induced thrombocytopenia": "Thrombocytopenia",

    # ── NEPHROLOGY ──────────────────────────────────────────────
    "acute kidney injury": "Acute Kidney Injury",
    "chronic kidney disease": "Renal Insufficiency, Chronic",
    "nephrotic syndrome": "Nephrotic Syndrome",
    "nephritic syndrome": "Nephritis",
    "glomerulonephritis": "Glomerulonephritis",
    "rhabdomyolysis": "Rhabdomyolysis",
    "nephrolithiasis": "Nephrolithiasis",

    # ── RHEUMATOLOGY ────────────────────────────────────────────
    "systemic lupus erythematosus": "Lupus Erythematosus, Systemic",
    "rheumatoid arthritis": "Arthritis, Rheumatoid",
    "gout": "Gout",
    "reactive arthritis": "Arthritis, Reactive",
    "ankylosing spondylitis": "Spondylitis, Ankylosing",
    "polymyalgia rheumatica": "Polymyalgia Rheumatica",
    "giant cell arteritis": "Giant Cell Arteritis",
    "dermatomyositis": "Dermatomyositis",
    "systemic sclerosis": "Scleroderma, Systemic",
    "vasculitis": "Vasculitis",
    "sarcoidosis": "Sarcoidosis",
    "behcet disease": "Behcet Syndrome",
    "kawasaki disease": "Mucocutaneous Lymph Node Syndrome",
    "antiphospholipid syndrome": "Antiphospholipid Syndrome",

    # ── PSYCHIATRY ──────────────────────────────────────────────
    "major depressive disorder": "Depressive Disorder, Major",
    "bipolar disorder": "Bipolar Disorder",
    "schizophrenia": "Schizophrenia",
    "psychosis": "Psychotic Disorders",
    "psychotic disorders": "Psychotic Disorders",
    "obsessive-compulsive disorder": "Obsessive-Compulsive Disorder",
    "ptsd": "Stress Disorders, Post-Traumatic",
    "anorexia nervosa": "Anorexia Nervosa",
    "bulimia nervosa": "Bulimia Nervosa",

    # ── OB/GYN ──────────────────────────────────────────────────
    "ectopic pregnancy": "Pregnancy, Ectopic",
    "preeclampsia": "Pre-Eclampsia",
    "eclampsia": "Eclampsia",
    "hellp syndrome": "HELLP Syndrome",
    "hyperemesis gravidarum": "Hyperemesis Gravidarum",
    "ovarian torsion": "Torsion, Ovary",
    "pelvic inflammatory disease": "Pelvic Inflammatory Disease",

    # ── TOXICOLOGY ──────────────────────────────────────────────
    "organophosphate poisoning": "Organophosphate Poisoning",
    "serotonin syndrome": "Serotonin Syndrome",
    "neuroleptic malignant syndrome": "Neuroleptic Malignant Syndrome",
    "malignant hyperthermia": "Malignant Hyperthermia",
    "carbon monoxide poisoning": "Carbon Monoxide Poisoning",
    "alcohol withdrawal": "Alcohol Withdrawal Delirium",
    "delirium tremens": "Alcohol Withdrawal Delirium",
    "acetaminophen overdose": "Acetaminophen",
    # Extended toxicology MeSH
    "salicylate toxicity": "Salicylates",
    "salicylate poisoning": "Salicylates",
    "methyl salicylate": "Salicylates",
    "methyl salicylate toxicity": "Salicylates",
    "wintergreen oil": "Salicylates",
    "aspirin poisoning": "Aspirin",
    "aspirin overdose": "Aspirin",
    "methanol poisoning": "Methanol",
    "ethylene glycol poisoning": "Ethylene Glycol",
    "cyanide poisoning": "Cyanides",
    "lead poisoning": "Lead Poisoning",
    "arsenic poisoning": "Arsenic Poisoning",
    "mercury poisoning": "Mercury Poisoning",
    "iron poisoning": "Iron",
    "lithium toxicity": "Lithium",
    "digoxin toxicity": "Digoxin",
    "opioid overdose": "Opiate Overdose",
    "benzodiazepine overdose": "Benzodiazepines",
    "tricyclic antidepressant toxicity": "Antidepressive Agents, Tricyclic",
    "beta blocker toxicity": "Adrenergic beta-Antagonists",
    "calcium channel blocker toxicity": "Calcium Channel Blockers",
    "snake envenomation": "Snake Bites",
    "scorpion envenomation": "Scorpion Stings",
    "mushroom poisoning": "Mushroom Poisoning",
    "methemoglobinemia": "Methemoglobinemia",
    "hydrogen sulfide poisoning": "Hydrogen Sulfide",
    "strychnine poisoning": "Strychnine",
    "thallium poisoning": "Thallium",
    "warfarin overdose": "Warfarin",
    "anticholinergic toxicity": "Cholinergic Antagonists",
    "cholinergic crisis": "Cholinergic Agents",
    "poisoning": "Poisoning",
    "drug overdose": "Drug Overdose",
    "toxidrome": "Poisoning",
    "antidote": "Antidotes",

    # ── EMERGENCY ───────────────────────────────────────────────
    "anaphylaxis": "Anaphylaxis",
    "cardiac arrest": "Heart Arrest",
    "shock": "Shock",
    "burns": "Burns",
    "hypothermia": "Hypothermia",
    "heat stroke": "Heat Stroke",
    "compartment syndrome": "Compartment Syndromes",
    "fat embolism": "Embolism, Fat",
    "vomiting": "Vomiting",

    # ── TUMORS ──────────────────────────────────────────────────
    "dermoid cyst": "Dermoid Cyst",
    "teratoma": "Teratoma",
    "ovarian cyst": "Ovarian Cysts",
    "brain neoplasm": "Brain Neoplasms",
    "glioblastoma": "Glioblastoma",
    "meningioma": "Meningioma",
    "pancreatic cancer": "Pancreatic Neoplasms",

    # ── GENERAL SYMPTOMS ────────────────────────────────────────
    "fever": "Fever",
    "cough": "Cough",
    "chest pain": "Chest Pain",
    "headache": "Headache",
    "back pain": "Back Pain",
    "edema": "Edema",
    "dyspnea": "Dyspnea",
    "syncope": "Syncope",
    "diarrhea": "Diarrhea",
    "jaundice": "Jaundice",
    "hematuria": "Hematuria",
    "proteinuria": "Proteinuria",

    # ── LEGACY (botulism details from original) ─────────────────
    "clostridium botulinum": "Clostridium botulinum",
    "flaccid paralysis": "Paralysis, Flaccid",
    "descending paralysis": "Paralysis",
    "ptosis": "Blepharoptosis",
    "dysarthria": "Dysarthria",
    "dysphagia": "Deglutition Disorders",
    "antitoxin": "Antitoxins",
    "foodborne diseases": "Foodborne Diseases",
    "food poisoning": "Foodborne Diseases",
    "hallucinations": "Hallucinations",
    "automatism": "Automatism",
    "nmda receptor": "Receptors, N-Methyl-D-Aspartate",
    "autonomic dysfunction": "Autonomic Nervous System Diseases",
    "thrombosis": "Thrombosis",
    "embolism": "Embolism",
    "diabetes": "Diabetes Mellitus",
    "lupus": "Lupus Erythematosus, Systemic",
}


# ═══════════════════════════════════════════════════════════════════════════
# BROAD CATEGORIES — Maps specific diagnoses to broader search terms.
# Used for SMART RETRY: when a specific query returns 0 results,
# instead of just removing words, try the broader category.
#
# Format: "specific_term_lower" → "broader search terms"
# ═══════════════════════════════════════════════════════════════════════════

BROAD_CATEGORIES: dict[str, str] = {
    # Cardiology
    "myocardial infarction": "acute coronary syndrome",
    "stemi": "acute coronary syndrome",
    "nstemi": "acute coronary syndrome",
    "unstable angina": "acute coronary syndrome",
    "dilated cardiomyopathy": "cardiomyopathy heart failure",
    "hypertrophic cardiomyopathy": "cardiomyopathy",
    "cardiac tamponade": "pericardial disease",
    "aortic dissection": "aortic disease emergency",

    # Neurology
    "wernicke encephalopathy": "encephalopathy nutritional deficiency vitamin",
    "wernicke-korsakoff syndrome": "encephalopathy thiamine deficiency vitamin B1",
    "korsakoff syndrome": "amnesia thiamine deficiency",
    "anti-nmda receptor encephalitis": "autoimmune encephalitis antibody-mediated",
    "herpes simplex encephalitis": "viral encephalitis",
    "autoimmune encephalitis": "encephalitis antibody-mediated",
    "guillain-barre syndrome": "autoimmune neuropathy acute inflammatory demyelinating",
    "status epilepticus": "seizure emergency",
    "subarachnoid hemorrhage": "intracranial hemorrhage cerebrovascular",
    "normal pressure hydrocephalus": "hydrocephalus dementia gait",
    "cerebral venous thrombosis": "intracranial thrombosis",
    "brain abscess": "intracranial infection focal neurological",
    "bell palsy": "facial paralysis cranial nerve",
    "botulism": "descending paralysis food-borne neurotoxin",

    # GI
    "acute pancreatitis": "pancreatitis abdominal emergency",
    "cholangitis": "biliary infection",
    "esophageal variceal hemorrhage": "gastrointestinal bleeding portal hypertension",
    "crohn disease": "inflammatory bowel disease",
    "ulcerative colitis": "inflammatory bowel disease",

    # Endocrine
    "diabetic ketoacidosis": "diabetes metabolic emergency acidosis",
    "thyroid storm": "thyrotoxicosis hyperthyroidism emergency",
    "myxedema coma": "hypothyroidism emergency",
    "adrenal crisis": "adrenal insufficiency emergency",
    "pheochromocytoma": "catecholamine-secreting tumor hypertension",
    "siadh": "hyponatremia water balance",

    # Infectious
    "lemierre syndrome": "septic thrombophlebitis jugular vein",
    "necrotizing fasciitis": "soft tissue infection surgical emergency",
    "meningococcemia": "meningococcal disease sepsis",
    "miliary tuberculosis": "disseminated tuberculosis",
    "pneumocystis pneumonia": "opportunistic infection immunocompromised",

    # Hematology
    "thrombotic thrombocytopenic purpura": "microangiopathic hemolytic anemia thrombocytopenia",
    "hemolytic uremic syndrome": "microangiopathic hemolytic anemia renal",
    "disseminated intravascular coagulation": "coagulopathy consumption",
    "heparin-induced thrombocytopenia": "drug-induced thrombocytopenia",

    # Rheumatology
    "systemic lupus erythematosus": "autoimmune multi-system connective tissue disease",
    "granulomatosis with polyangiitis": "ANCA vasculitis",
    "antiphospholipid syndrome": "thrombophilia autoimmune",
    "behcet disease": "vasculitis mucocutaneous",

    # Toxicology
    "serotonin syndrome": "drug toxicity hyperthermia",
    "neuroleptic malignant syndrome": "drug reaction hyperthermia rigidity",
    "organophosphate poisoning": "cholinergic toxicity pesticide",
    "carbon monoxide poisoning": "toxic gas inhalation",
    # Extended toxicology broad categories
    "methyl salicylate toxicity": "salicylate poisoning treatment",
    "methyl salicylate poisoning": "salicylate toxicity emergency",
    "wintergreen oil toxicity": "salicylate poisoning",
    "salicylate toxicity": "salicylate poisoning treatment emergency",
    "salicylate poisoning": "aspirin toxicity treatment",
    "aspirin overdose": "salicylate poisoning emergency",
    "methanol poisoning": "toxic alcohol poisoning treatment",
    "ethylene glycol poisoning": "toxic alcohol poisoning treatment",
    "cyanide poisoning": "chemical poisoning antidote emergency",
    "lead poisoning": "heavy metal poisoning chelation",
    "arsenic poisoning": "heavy metal poisoning",
    "mercury poisoning": "heavy metal poisoning",
    "iron poisoning": "metal poisoning deferoxamine",
    "lithium toxicity": "drug toxicity electrolyte",
    "digoxin toxicity": "cardiac glycoside toxicity",
    "acetaminophen overdose": "drug overdose hepatotoxicity NAC",
    "opioid overdose": "drug overdose naloxone",
    "benzodiazepine overdose": "sedative overdose flumazenil",
    "tricyclic antidepressant toxicity": "drug overdose cardiac toxicity",
    "methemoglobinemia": "hemoglobin oxidation cyanosis",
    "hydrogen sulfide poisoning": "toxic gas inhalation",
    "mushroom poisoning": "food poisoning hepatotoxicity",
    "snake envenomation": "animal bite antivenom",
    "beta blocker toxicity": "drug overdose bradycardia hypotension",
    "calcium channel blocker toxicity": "drug overdose bradycardia hypotension",

    # OB/GYN
    "ectopic pregnancy": "acute abdomen pregnancy first trimester",
    "hellp syndrome": "pregnancy-related liver thrombocytopenia",
    "eclampsia": "hypertensive pregnancy emergency seizure",

    # Nutrition
    "refeeding syndrome": "metabolic complication malnutrition",
    "beriberi": "thiamine deficiency cardiovascular neurological",
    "pellagra": "niacin deficiency dermatitis diarrhea dementia",
    "scurvy": "vitamin C deficiency",
    "subacute combined degeneration": "vitamin B12 deficiency myelopathy",
}


# ═══════════════════════════════════════════════════════════════════════════
# FILLER WORDS — Conversational noise to strip from medical queries.
# Used across all tool optimizers.
# ═══════════════════════════════════════════════════════════════════════════

QUERY_FILLER_WORDS: set[str] = {
    "differentiation", "between", "versus", "vs", "patterns",
    "assessment", "evaluation", "characteristics", "features",
    "specific", "general", "overview", "comprehensive",
    "detailed", "particular", "regarding", "related",
    "associated", "common", "typical", "clinical",
    "management", "approach", "strategy", "options",
    "available", "current", "recent", "latest",
    "possible", "potential", "various", "different",
    "including", "especially", "particularly", "mainly",
    "primarily", "often", "usually", "generally",
    "canned", "commercial", "homemade", "source",
    "presentation", "findings", "workup", "initial",
    "diagnostic", "differential", "diagnosis", "treatment",
    "and", "the", "with", "for", "from", "this", "that",
    "patient", "case", "history", "examine", "review",
}

EPMC_FILLER_WORDS: set[str] = {
    "and", "the", "with", "for", "from", "versus", "between", "related",
    "associated", "specific", "general", "differential", "diagnosis",
    "assessment", "evaluation", "management", "approach", "overview",
    "comprehensive", "detailed", "particular", "regarding", "pattern",
    "possible", "potential", "various", "different", "including", "options",
}


# ═══════════════════════════════════════════════════════════════════════════
# CASE CATEGORY KEYWORDS — Dynamic case type detection.
# Maps medical category → set of keywords. When R1 diagnosis text contains
# these keywords, we know the case type and can apply category-specific
# search strategies (e.g. MeSH subheadings, query patterns).
#
# This is DYNAMIC — new categories or keywords can be added without
# changing any code logic.
# ═══════════════════════════════════════════════════════════════════════════

CASE_CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "toxicology": [
        "toxicity", "poisoning", "overdose", "intoxication", "toxic",
        "exposure", "ingestion", "inhalation", "envenomation", "toxidrome",
        "antidote", "chelation", "decontamination",
        "zehirlenme", "zehir", "doz aşımı", "maruziyet",
    ],
    "infectious": [
        "infection", "sepsis", "septicemia", "bacteremia", "abscess",
        "pneumonia", "meningitis", "encephalitis", "cellulitis",
        "endocarditis", "osteomyelitis", "pyelonephritis", "tuberculosis",
        "malaria", "dengue", "HIV", "hepatitis",
        "enfeksiyon", "apse", "sepsis",
    ],
    "autoimmune": [
        "autoimmune", "antibody", "lupus", "vasculitis", "rheumatoid",
        "anti-nmda", "paraneoplastic", "scleroderma", "dermatomyositis",
        "sarcoidosis", "behcet", "antiphospholipid",
        "otoimmün",
    ],
    "neoplastic": [
        "cancer", "carcinoma", "lymphoma", "leukemia", "neoplasm",
        "tumor", "malignancy", "metastasis", "mass", "sarcoma",
        "myeloma", "melanoma", "adenocarcinoma",
        "kanser", "tümör",
    ],
    "nutritional": [
        "deficiency", "malnutrition", "thiamine", "vitamin", "beriberi",
        "wernicke", "korsakoff", "pellagra", "scurvy", "folate",
        "refeeding", "marasmus", "kwashiorkor",
        "eksiklik", "beslenme",
    ],
    "metabolic": [
        "ketoacidosis", "acidosis", "alkalosis", "hypoglycemia",
        "hyperglycemia", "hyponatremia", "hyperkalemia", "metabolic",
        "electrolyte", "acid-base", "rhabdomyolysis", "uremia",
        "asidoz", "metabolik",
    ],
    "cardiovascular": [
        "infarction", "embolism", "thrombosis", "dissection", "tamponade",
        "arrhythmia", "fibrillation", "heart failure", "cardiomyopathy",
        "endocarditis", "pericarditis", "myocarditis", "aneurysm",
        "enfarktüs", "emboli", "tromboz",
    ],
    "neurological": [
        "stroke", "hemorrhage", "encephalopathy", "neuropathy", "seizure",
        "paralysis", "meningitis", "encephalitis", "hydrocephalus",
        "demyelinating", "guillain", "myasthenia", "botulism",
        "inme", "nöbet", "felç",
    ],
    "respiratory": [
        "pneumonia", "pneumothorax", "embolism", "ards", "asthma",
        "copd", "fibrosis", "effusion", "hemoptysis", "respiratory",
        "pnömoni", "pnömotoraks", "astım",
    ],
    "trauma": [
        "fracture", "laceration", "contusion", "hemorrhage", "burn",
        "crush", "compartment syndrome", "concussion", "spinal",
        "kırık", "yanık", "travma",
    ],
}


# ═══════════════════════════════════════════════════════════════════════════
# MESH SUBHEADINGS — Category-specific MeSH subheadings for PubMed.
# When a case falls into a category, these subheadings are applied to the
# first MeSH term to produce more targeted queries.
#
# E.g. toxicology → "poisoning" → "Salicylates/poisoning"[MeSH]
# E.g. infectious → "drug therapy" → "Meningitis/drug therapy"[MeSH]
#
# Format: category → list of subheading names (first = highest priority)
# ═══════════════════════════════════════════════════════════════════════════

MESH_SUBHEADINGS: dict[str, list[str]] = {
    "toxicology": ["poisoning", "toxicity", "adverse effects"],
    "infectious": ["drug therapy", "microbiology", "diagnosis"],
    "autoimmune": ["immunology", "diagnosis", "drug therapy"],
    "neoplastic": ["diagnosis", "therapy", "pathology"],
    "nutritional": ["deficiency", "metabolism", "diet therapy"],
    "metabolic": ["metabolism", "blood", "diagnosis"],
    "cardiovascular": ["diagnosis", "therapy", "complications"],
    "neurological": ["diagnosis", "etiology", "drug therapy"],
    "respiratory": ["diagnosis", "therapy", "etiology"],
    "trauma": ["surgery", "therapy", "complications"],
}
